ALTER TABLE solicitacoes_saque
ALTER COLUMN valor DROP NOT NULL,
ADD COLUMN IF NOT EXISTS quantidade INTEGER,
ADD COLUMN IF NOT EXISTS atividade TEXT,
ADD COLUMN IF NOT EXISTS descricao TEXT,
ADD COLUMN IF NOT EXISTS comprovante_url TEXT,
ADD COLUMN IF NOT EXISTS tipo TEXT DEFAULT 'saque_pipj';
